# Generated by Django 4.2.6 on 2023-10-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_watchbutton'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField()),
            ],
        ),
    ]
