# Generated by Django 4.2.6 on 2023-10-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateField(),
        ),
    ]
