# Generated by Django 4.2.6 on 2023-10-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_end_time_alter_game_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
