# Generated by Django 4.2.6 on 2023-10-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_end_time_alter_game_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchbutton',
            name='name',
            field=models.CharField(default=''),
        ),
    ]
