# Generated by Django 4.2.6 on 2023-10-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_watchbutton_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchbutton',
            name='name',
            field=models.CharField(),
        ),
    ]
