# Generated by Django 4.2.6 on 2023-10-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_watchbutton_name_in_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchbutton',
            name='name_in_page',
            field=models.CharField(),
        ),
    ]
