# Generated by Django 4.2.6 on 2023-10-19 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_watchbutton_name_in_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championship',
            options={'verbose_name': 'Campeonato', 'verbose_name_plural': 'Campeonatos'},
        ),
        migrations.AlterModelOptions(
            name='configuration',
            options={'verbose_name': 'Configuração', 'verbose_name_plural': 'Configurações'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Jogo', 'verbose_name_plural': 'Jogos'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Time', 'verbose_name_plural': 'Times'},
        ),
        migrations.AlterModelOptions(
            name='watchbutton',
            options={'verbose_name': 'Botão Assistir', 'verbose_name_plural': 'Botões Assistir'},
        ),
        migrations.RemoveField(
            model_name='watchbutton',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='watch_buttons',
            field=models.ManyToManyField(to='games.watchbutton'),
        ),
        migrations.AlterField(
            model_name='championship',
            name='image_url',
            field=models.CharField(verbose_name='url da imagem'),
        ),
        migrations.AlterField(
            model_name='championship',
            name='name',
            field=models.CharField(verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='header',
            field=models.CharField(verbose_name='cabeçalho'),
        ),
        migrations.AlterField(
            model_name='game',
            name='championship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.championship', verbose_name='campeonato'),
        ),
        migrations.AlterField(
            model_name='game',
            name='end_time',
            field=models.TimeField(verbose_name='final'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='games.team', verbose_name='time mandante'),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.TimeField(verbose_name='inicio'),
        ),
        migrations.AlterField(
            model_name='game',
            name='visiting_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visiting_team', to='games.team', verbose_name='time visitante'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image_url',
            field=models.CharField(verbose_name='url da imagem'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='watchbutton',
            name='name',
            field=models.CharField(verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='watchbutton',
            name='name_in_page',
            field=models.CharField(blank=True, verbose_name='nome na página'),
        ),
    ]
