# Generated by Django 4.2.6 on 2023-10-19 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_alter_championship_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='watch_buttons',
        ),
        migrations.AddField(
            model_name='watchbutton',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
    ]
